stages:
  - test
  - build

syntax_check:
  stage: test
  image: python:3.9-slim
  script:
    - pip install -r requirements.txt
    - python -m py_compile $(find . -name "*.py")

build_check:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker compose up -d --build