# prometheus.yml
global:
  scrape_interval: 5s  # coleta a cada 5 segundos

scrape_configs:
  - job_name: "app-votacao"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["app-votacao:5000"]

grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge
